<?php

namespace common\models\forms;

use common\models\ApplicationForm;
use common\models\Districts;
use common\models\Regions;
use common\models\WorldCountries;
use Yii;

/**
 * This is the model class for table "author_application".
 *
 * @property int $id
 * @property int|null $user_id
 * @property int|null $user_application_id
 * @property int|null $user_application_wizard_id
 * @property int|null $author_country_code
 * @property string|null $jshshir
 * @property string|null $full_name
 * @property int|null $region
 * @property int|null $district
 * @property int|null $is_anonymous
 * @property string|null $address
 * @property string|null $workplace
 * @property string|null $position
 * @property string|null $nickname
 */
class FormAuthor extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'form_author';
    }
    const CLASS_FORM_ID = 2;
    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['user_id', 'user_application_id', 'user_application_wizard_id', 'author_country_code', 'region', 'district','is_anonymous'], 'integer'],
            [['jshshir', 'full_name', 'address', 'workplace', 'position','nickname'], 'string', 'max' => 255],
            [['academic_degree'], 'string', 'max' => 150],
        ];
    }

/*    public function beforeSave($insert)
    {
        $maxId = self::find()->max('id');
        $this->id = $maxId + 1;
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }*/

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'user_id' => Yii::t('app', 'User ID'),
            'user_application_id' => Yii::t('app', 'User Application ID'),
            'user_application_wizard_id' => Yii::t('app', 'User Application Wizard ID'),
            'author_country_code' => Yii::t('app', 'Author Country Code'),
            'jshshir' => Yii::t('app', 'Jshshir'),
            'full_name' => Yii::t('app', 'Full Name'),
            'region' => Yii::t('app', 'Region'),
            'district' => Yii::t('app', 'District'),
            'address' => Yii::t('app', 'Address'),
            'workplace' => Yii::t('app', 'Workplace'),
            'position' => Yii::t('app', 'Position'),
            'academic_degree' => Yii::t('app', 'Academic Degree'),
            'is_anonymous',
            'nickname',
        ];
    }

     public static function run($user_id, $application_id, $wizard_id,$form_id=null)
    {
        return self::findAll([
            'user_application_id'=>$application_id,
            'user_id' => $user_id,
            'user_application_wizard_id' =>$wizard_id,
        ]);
    }

    public function fields()
    {
        return [
            'form_id' => function () {
                return ApplicationForm::findOne(['form_class'=>get_called_class()])->id;
            },
            'id',
            'user_id',
            'user_application_id',
            'user_application_wizard_id',
            'jshshir',
            'full_name',
            'district' => function () {
                $address = Districts::findOne($this->district);
                return $address ? [
                    'id' => $this->region,
                    'name' => $address->name_uz,
                ] : [];
            },
            'region' => function () {
                $address = Regions::findOne($this->region);
                return $address ? [
                    'id' => $this->region,
                    'name' => $address->name_uz,
                ] : [];
            },
            'author_country_code' => function () {
                $submittingCountry = WorldCountries::findOne($this->author_country_code);
                return [
                    'id' => $this->author_country_code,
                    'code' => $submittingCountry->country_code,
                    'country_name' => $submittingCountry->country_name,
                ];
            },
            'address',
            'workplace',
            'position',
            'academic_degree',
            'is_anonymous',
            'nickname',
        ];
    }

    /**
     * {@inheritdoc}
     * @return \common\models\query\AuthorApplicationQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\query\AuthorApplicationQuery(get_called_class());
    }
}
